name: MainController Docker CI

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'MainController/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'MainController/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - 
      name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Publish the Docker image
      run: |
              docker build -t ghcr.io/amt-team03/main-controller:latest ./MainController/
              docker push ghcr.io/amt-team03/main-controller:latest