name: ObjectManager Docker CI

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'ObjectManager/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'ObjectManager/**'

jobs:
  build:
    environment: CI-AWS
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Github Container Registry
    uses: docker/login-action@v2
      with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Publish the Docker image 
      run: |
              docker build -t AMT/object-manager:latest --build-arg aws_access_key_id=$AWS_ACCESS_KEY_ID --build-arg aws_secret_access_key=$AWS_SECRET_ACCESS_KEY ./ObjectManager/
              docker run AMT/object-manager:latest
              docker push AMT/object-manager:latest